var chainmarket_beibei={
"RECORDS":[
{
"id":"B00170B8IM",
"name":"环宇连锁超市(凤翔路店)",
"type":"购物服务;便民商店\/便利店;便民商店\/便利店",
"typecode":"060200",
"biz_type":"[]",
"address":"含谷镇建新村二社",
"location":"106.466440,29.463466",
"tel":"18584508793",
"distance":"[]",
"biz_ext":"[]",
"pname":"重庆市",
"cityname":"重庆市",
"adname":"大渡口区",
"importance":"[]",
"shopid":"[]",
"shopinfo":"0",
"poiweight":"[]",
"parking_type":null,
"avg_price":null,
"avg_price_type":null
},
{
"id":"B0FFH8O7BT",
"name":"心连心连锁超市",
"type":"购物服务;超级市场;超市",
"typecode":"060400",
"biz_type":"[]",
"address":"茄子溪正街227号",
"location":"106.495130,29.429281",
"tel":"[]",
"distance":"[]",
"biz_ext":"[]",
"pname":"重庆市",
"cityname":"重庆市",
"adname":"大渡口区",
"importance":"[]",
"shopid":"[]",
"shopinfo":"0",
"poiweight":"[]",
"parking_type":null,
"avg_price":null,
"avg_price_type":null
}
]
}